AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  Environment:
    Type: String
    Description: "The environment for the deployment (dev or prod)"
    AllowedValues:
      - dev
      - prod
    Default: dev
    ConstraintDescription: "Must be either 'dev' or 'prod'."
  S3Key:
    Type: String
    Description: The S3 key for the lambda function zip file.

Resources:
  OneHundredLettersAuthorizerFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "one-hundred-letters-authorizer-${Environment}"
      Runtime: nodejs20.x
      Role:
        Fn::ImportValue: !Sub "LambdaExecutionOneHundredLettersAuthorizerArn-${Environment}"
      Handler: index.handler
      Code:
        S3Bucket:
          Fn::ImportValue: !Sub "OneHundredLettersAuthorizerBucketName-${Environment}"
        S3Key: !Ref S3Key
      Timeout: 5
      MemorySize: 128
      
  MyLambdaVersion:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref OneHundredLettersAuthorizerFunction

  AllowApiGatewayToInvokeAuthAtEdge:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref OneHundredLettersAuthorizerFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com

Outputs:
  OneHundredLettersAuthorizerFunctionArn:
    Description: "ARN of the authorizer function"
    Value: !GetAtt MyLambdaVersion.FunctionArn 
    Export:
      Name: !Sub "OneHundredLettersAuthorizerFunctionArn-${Environment}"
